"""Full hero roster (current 2026 pool) used to expand the hero database.

The curated `HEROES` list in seed.py keeps detailed internal notes for the
heroes 9 CLOVER actually tracks; every other hero here gets a sensible
baseline row so the database is complete for drafts, pools and the ban board.

Icon slugs (frontend/public/heroes/<slug>.webp) are derived in the UI:
name.lower() with spaces/apostrophes → dashes.
"""
from __future__ import annotations

# (name, lane, class(faction), difficulty 1-10)
ROSTER: list[tuple[str, str, str, int]] = [
    # ----------------------------- EXP -------------------------------------
    ("Aldous", "EXP", "Fighter", 5),
    ("Argus", "EXP", "Fighter", 3),
    ("Arlott", "EXP", "Fighter", 7),
    ("Aulus", "EXP", "Fighter", 3),
    ("Badang", "EXP", "Fighter", 4),
    ("Benedetta", "EXP", "Assassin", 7),
    ("Chou", "EXP", "Fighter", 5),
    ("Cici", "EXP", "Marksman", 4),
    ("Dyrroth", "EXP", "Fighter", 3),
    ("Esmeralda", "EXP", "Mage/Fighter", 6),
    ("Freya", "EXP", "Fighter", 4),
    ("Gatotkaca", "EXP", "Tank", 3),
    ("Gloo", "EXP", "Tank", 5),
    ("Guinevere", "EXP", "Fighter/Mage", 5),
    ("Jawhead", "EXP", "Fighter", 5),
    ("Khaleed", "EXP", "Fighter", 4),
    ("Lapu-Lapu", "EXP", "Fighter", 5),
    ("Lukas", "EXP", "Fighter", 4),
    ("Masha", "EXP", "Fighter/Tank", 4),
    ("Minsitthar", "EXP", "Fighter", 4),
    ("Paquito", "EXP", "Fighter/Assassin", 7),
    ("Phoveus", "EXP", "Fighter", 4),
    ("Ruby", "EXP", "Fighter", 5),
    ("Silvanna", "EXP", "Fighter/Mage", 5),
    ("Sun", "EXP", "Fighter", 4),
    ("Terizla", "EXP", "Fighter", 4),
    ("Thamuz", "EXP", "Fighter", 3),
    ("Uranus", "EXP", "Tank", 3),
    ("X.Borg", "EXP", "Fighter", 5),
    ("Yin", "EXP", "Fighter/Assassin", 5),
    ("Sora", "EXP", "Fighter/Assassin", 5),
    ("Yu Zhong", "EXP", "Fighter", 6),
    ("Zilong", "EXP", "Fighter", 3),
    # ----------------------------- JUNGLE ----------------------------------
    ("Hirara", "JUNGLE", "Assassin", 7),
    ("Aamon", "JUNGLE", "Assassin", 6),
    ("Akai", "JUNGLE", "Tank", 4),
    ("Alucard", "JUNGLE", "Fighter", 3),
    ("Alpha", "JUNGLE", "Fighter", 4),
    ("Balmond", "JUNGLE", "Fighter", 2),
    ("Bane", "JUNGLE", "Fighter", 3),
    ("Barats", "JUNGLE", "Tank/Fighter", 5),
    ("Fanny", "JUNGLE", "Assassin", 10),
    ("Fredrinn", "JUNGLE", "Tank", 5),
    ("Gusion", "JUNGLE", "Assassin/Mage", 8),
    ("Hanzo", "JUNGLE", "Assassin", 6),
    ("Hayabusa", "JUNGLE", "Assassin", 7),
    ("Helcurt", "JUNGLE", "Assassin", 5),
    ("Joy", "JUNGLE", "Assassin", 7),
    ("Karina", "JUNGLE", "Assassin", 5),
    ("Lancelot", "JUNGLE", "Assassin", 8),
    ("Leomord", "JUNGLE", "Fighter", 5),
    ("Ling", "JUNGLE", "Assassin", 8),
    ("Martis", "JUNGLE", "Fighter", 4),
    ("Nolan", "JUNGLE", "Assassin", 6),
    ("Roger", "JUNGLE", "Fighter/Marksman", 5),
    ("Saber", "JUNGLE", "Assassin", 3),
    ("Suyou", "JUNGLE", "Fighter/Assassin", 6),
    ("Wasp", "JUNGLE", "Assassin", 6),
    # ----------------------------- MID --------------------------------------
    ("Alice", "MID", "Mage/Tank", 4),
    ("Aurora", "MID", "Mage", 3),
    ("Cecilion", "MID", "Mage", 5),
    ("Chang'e", "MID", "Mage", 3),
    ("Cyclops", "MID", "Mage", 3),
    ("Eudora", "MID", "Mage", 2),
    ("Faramis", "MID", "Support/Mage", 4),
    ("Gord", "MID", "Mage", 2),
    ("Harley", "MID", "Mage/Assassin", 5),
    ("Julian", "MID", "Fighter/Mage", 7),
    ("Kadita", "MID", "Mage/Assassin", 6),
    ("Kagura", "MID", "Mage", 8),
    ("Lunox", "MID", "Mage", 6),
    ("Luo Yi", "MID", "Mage", 5),
    ("Lylia", "MID", "Mage", 5),
    ("Nana", "MID", "Mage", 2),
    ("Novaria", "MID", "Mage", 5),
    ("Odette", "MID", "Mage", 3),
    ("Pharsa", "MID", "Mage", 4),
    ("Valentina", "MID", "Mage", 7),
    ("Vale", "MID", "Mage", 2),
    ("Valir", "MID", "Mage", 4),
    ("Vexana", "MID", "Mage", 3),
    ("Xavier", "MID", "Mage", 5),
    ("Yve", "MID", "Mage", 5),
    ("Dori", "MID", "Mage", 1),
    ("Zetian", "MID", "Mage", 6),
    ("Zhask", "MID", "Mage", 4),
    ("Zhuxin", "MID", "Mage", 4),
    # ----------------------------- GOLD -------------------------------------
    ("Obsidia", "GOLD", "Marksman", 5),
    ("Beatrix", "GOLD", "Marksman", 5),
    ("Brody", "GOLD", "Marksman", 4),
    ("Bruno", "GOLD", "Marksman", 4),
    ("Claude", "GOLD", "Marksman", 6),
    ("Clint", "GOLD", "Marksman", 4),
    ("Granger", "GOLD", "Marksman", 5),
    ("Hanabi", "GOLD", "Marksman", 3),
    ("Harith", "GOLD", "Mage", 7),
    ("Irithel", "GOLD", "Marksman", 4),
    ("Ixia", "GOLD", "Marksman", 4),
    ("Karrie", "GOLD", "Marksman", 5),
    ("Kimmy", "GOLD", "Marksman/Mage", 6),
    ("Layla", "GOLD", "Marksman", 1),
    ("Lesley", "GOLD", "Marksman/Assassin", 4),
    ("Melissa", "GOLD", "Marksman", 4),
    ("Miya", "GOLD", "Marksman", 2),
    ("Moskov", "GOLD", "Marksman", 6),
    ("Natan", "GOLD", "Marksman", 5),
    ("Popol and Kupa", "GOLD", "Marksman", 6),
    ("Wanwan", "GOLD", "Marksman", 7),
    ("Yi Sun-shin", "GOLD", "Marksman/Assassin", 5),
    # ----------------------------- ROAM -------------------------------------
    ("Marcel", "ROAM", "Support", 3),
    ("Angela", "ROAM", "Support", 4),
    ("Atlas", "ROAM", "Tank", 6),
    ("Baxia", "ROAM", "Tank", 4),
    ("Belerick", "ROAM", "Tank", 3),
    ("Carmilla", "ROAM", "Support/Tank", 4),
    ("Chip", "ROAM", "Tank", 6),
    ("Diggie", "ROAM", "Support", 3),
    ("Edith", "ROAM", "Tank/Marksman", 4),
    ("Estes", "ROAM", "Support", 2),
    ("Floryn", "ROAM", "Support", 3),
    ("Franco", "ROAM", "Tank", 5),
    ("Grock", "ROAM", "Tank", 4),
    ("Hilda", "ROAM", "Fighter/Tank", 3),
    ("Hylos", "ROAM", "Tank", 3),
    ("Johnson", "ROAM", "Tank/Support", 4),
    ("Kaja", "ROAM", "Support/Fighter", 4),
    ("Kalea", "ROAM", "Support", 5),
    ("Khufra", "ROAM", "Tank", 6),
    ("Lolita", "ROAM", "Support/Tank", 4),
    ("Mathilda", "ROAM", "Support/Assassin", 7),
    ("Minotaur", "ROAM", "Tank", 2),
    ("Natalia", "ROAM", "Assassin", 5),
    ("Rafaela", "ROAM", "Support", 2),
    ("Selena", "ROAM", "Assassin/Mage", 8),
    ("Tigreal", "ROAM", "Tank", 3),
]

# Internal meta read for the current patch: status / tier / 9 CLOVER rating
# for heroes that matter right now. Anything not listed lands as
# VIABLE / B / 5.5 and staff refine in the app.
TUNING: dict[str, tuple[str, str, float, str]] = {
    # keep pace with the curated rows in seed.py — these extend, not replace
    "Zetian": ("STRONG", "A", 7.5, "New-wave mage: global pressure + teamfight lockdown. Scout her in scrims."),
    "Kalea": ("STRONG", "A", 7.0, "Ripple heals swing long fights. Pair with sustain comps."),
    "Wasp": ("VIABLE", "B", 6.0, "Announced for an upcoming patch — not on live rankings yet. Track reveals, no scrim data."),
    "Dori": ("VIABLE", "B", 5.5, "Shepherd of Smiles — announced March-shepherd mage, TBA. Placeholder until release."),
    "Hirara": ("META", "S+", 9.0, "Fallen Scarlet (Jun 2026). Most-banned hero in the game — combo assassin, scrims treat as red-line ban."),
    "Marcel": ("META", "S+", 8.6, "Soul Photographer (Mar 2026). Time-freeze support; setup-heavy, ratings unstable on thin samples."),
    "Sora": ("VIABLE", "A", 7.2, "Shifting Cloud (Dec 2025). Form-swapping EXP: Thunder burst / Torrent frontline."),
    "Obsidia": ("META", "S+", 8.4, "New gold-lane power pick. Highest pick rate among S+ heroes; scout hard."),
    "Granger": ("STRONG", "A", 7.0, "Jungle-flex burst;punish his reload windows in trades."),
    "Brody": ("VIABLE", "A", 6.5, "Stack-hugger. Deny his passive in lane and he limps."),
    "Kimmy": ("VIABLE", "B", 5.5, "Hybrid poke; joins only with a dedicated plan."),
    "Clint": ("VIABLE", "B", 5.5, "Lane bully mid-game. Falls over late."),
    "Xavier": ("VIABLE", "A", 6.0, "Ult cross-map picks. Track his 4-charge windows."),
    "Cecilion": ("SITUATIONAL", "B", 5.0, "Late monster, dead weight before item two."),
    "X.Borg": ("VIABLE", "B", 6.0, "HP-swap fights reward setup. Niche vs burst."),
    "Luo Yi": ("VIABLE", "B", 6.0, "Combo depends on Patience marks — coordinated teams only."),
    "Kagura": ("STRONG", "A", 7.0, "Skill ceiling pays off in drafts with engage support."),
    "Julian": ("STRONG", "A", 7.5, "Mode-swapping brawler. Annoying enough to respect-ban vs some mids."),
    "Kadita": ("SITUATIONAL", "B", 5.5, "Combo one-shot or nothing. Fog-dependent."),
    "Aamon": ("STRONG", "A", 7.0, "Dagger rain melts objectives. Steal his rhythm with vision."),
    "Lancelot": ("STRONG", "A", 7.5, "Untouchable in good hands — point CC is the only answer."),
    "Gusion": ("SITUATIONAL", "A", 6.5, "Mechanics-heavy; only when SORA asks."),
    "Roger": ("STRONG", "A", 7.0, "Wolf-form dives erase backlines on tempo."),
    "Silvanna": ("VIABLE", "B", 5.5, "Honest pick. Middle of every tier list."),
    "Benedetta": ("STRONG", "A", 7.0, "Dash trades bully most EXP matchups."),
    "Uranus": ("VIABLE", "B", 5.5, "Regen sponge; dies to the same burst window every time."),
    "Edith": ("VIABLE", "B", 6.0, "Marksman-mode punish windows make her a draft flex."),
    "Natalia": ("SITUATIONAL", "B", 5.0, "Fog assassin for tilting games. Drafts must enable her."),
    "Hilda": ("SITUATIONAL", "B", 4.5, "Bush-cheese or bust."),
    "Popol and Kupa": ("VIABLE", "B", 6.0, "Map control duo. Trap-heavy space denial."),
    "Harith": ("SITUATIONAL", "B", 6.0, "Pocket into short-range comps."),
    "Moskov": ("SITUATIONAL", "B", 5.5, "Teleport chaos needs a written plan."),
    "Layla": ("WEAK", "C", 3.0, "No mobility = free dinner for divers."),
    "Hanabi": ("WEAK", "C", 3.0, "Energy-hungry and dive-delete. Skip."),
    "Miya": ("SITUATIONAL", "C", 3.5, "Only when the lobby is very low CC."),
    "Eudora": ("SITUATIONAL", "B", 4.0, "Simple burst. Fine into squishies."),
    "Gord": ("SITUATIONAL", "B", 4.0, "Static channel ults — dies to any flank."),
    "Diggie": ("STRONG", "A", 7.0, "Anti-CC cage erases whole ult investment. High-priority vs engage."),
    "Estes": ("SITUATIONAL", "B", 4.5, "Heal ball: strong when ahead, sad from behind."),
    "Carmilla": ("SITUATIONAL", "B", 4.5, "Link mechanic needs rehearsed follow-up."),
    "Belerick": ("SITUATIONAL", "B", 4.0, "Reflect niche vs basic-attack comps."),
    "Atlas": ("VIABLE", "B", 6.0, "Anchor ult wins choke fights. Map-dependent."),
    "Baxia": ("VIABLE", "B", 5.0, "Anti-heal rotations vs sustain drafts."),
    "Johnson": ("SITUATIONAL", "B", 5.0, "Uber driver. Tilt-classic."),
    "Minotaur": ("SITUATIONAL", "B", 4.0, "Rage-gated engage. Slow."),
    "Tigreal": ("VIABLE", "B", 5.5, "Free ult catches win games. Honest tank."),
    "Rafaela": ("SITUATIONAL", "B", 4.0, "Reveal aura tech vs fog teams."),
    "Zilong": ("WEAK", "C", 3.0, "Outstat-ed by modern fighters."),
    "Alucard": ("SITUATIONAL", "C", 3.5, "Feast-or-famine lifesteal."),
    "Balmond": ("SITUATIONAL", "C", 3.0, "Spin cheese falls to any peel."),
    "Sun": ("SITUATIONAL", "B", 4.5, "Clone pressure needs silence to thrive."),
    "Argus": ("SITUATIONAL", "B", 4.5, "Immortality gimmick — play around cd or lose."),
    "Thamuz": ("SITUATIONAL", "B", 4.0, "Scorched trail zones; kite him out."),
    "Faramis": ("SITUATIONAL", "B", 5.0, "Respawn ult combos with dive packages."),
    "Alice": ("SITUATIONAL", "B", 5.0, "Blood-orb scaling needs time the meta rarely gives."),
    "Harley": ("VIABLE", "B", 5.5, "Quick picks pre-objective. Fade as fights go 5v5."),
    "Odette": ("SITUATIONAL", "B", 4.5, "Channel ult = CC magnet."),
    "Cyclops": ("SITUATIONAL", "B", 4.5, "Spin-to-win needs setup."),
    "Vale": ("SITUATIONAL", "B", 4.5, "Zone mage on a budget."),
    "Valir": ("SITUATIONAL", "B", 4.5, "Counter-dash firewall. Drafted into divers."),
    "Aurora": ("SITUATIONAL", "B", 5.0, "Freeze combo punishes clumped teams."),
    "Nana": ("SITUATIONAL", "B", 4.5, "Molina nuke + revive. Cute, sometimes lethal."),
    "Lunox": ("VIABLE", "A", 6.0, "Tank melting + self-peel; weak into poke."),
    "Lapu-Lapu": ("VIABLE", "B", 5.5, "Stance-swapping brawler. Solid blind pick."),
    "Leomord": ("SITUATIONAL", "B", 4.5, "Mounted charge needs flank lanes."),
    "Yi Sun-shin": ("SITUATIONAL", "A", 6.0, "Global ult scouting — coordinator's pick."),
    "Natan": ("VIABLE", "B", 5.5, "Peak late-game DPS through his clones."),
    "Lesley": ("VIABLE", "B", 5.5, "Range+reload punishes short-range drafts."),
    "Irithel": ("VIABLE", "B", 5.0, "Moving shots;dodged by real meta divers."),
    "Barats": ("STRONG", "A", 6.5, "Body-block stacks make him a wall late."),
    "Martis": ("VIABLE", "B", 5.5, "Combo suppression; straight-line fights only."),
    "Hanzo": ("SITUATIONAL", "B", 5.0, "Body-swap risk/reward. Vision-dependent."),
    "Helcurt": ("SITUATIONAL", "B", 5.0, "Silence windows vs spell-heavy comps."),
    "Saber": ("SITUATIONAL", "B", 4.5, "Point-delete one target then spectator."),
    "Gatotkaca": ("VIABLE", "B", 5.0, "Avatar ult taunt zones. Slow but real."),
    "Gloo": ("SITUATIONAL", "B", 5.0, "Blob boy: tanky but kited forever."),
    "Masha": ("SITUATIONAL", "B", 4.5, "Triple-HP bars; dies to the same burst twice."),
    "Akai": ("VIABLE", "B", 5.5, "Spin goalie for pit dances. Composition piece."),
    "Jawhead": ("VIABLE", "B", 5.5, "Ejector cheese for picks; dive games."),
    "Khaleed": ("SITUATIONAL", "B", 4.5, "Sand surfing sustain; macro-limited."),
    "Aulus": ("SITUATIONAL", "B", 4.0, "Axe stacks ramp too slowly for tempo games."),
    "Badang": ("SITUATIONAL", "B", 4.5, "Wall combos vs immobile carries."),
    "Aldous": ("SITUATIONAL", "B", 5.0, "Stacking fantasy; global ult pressure is real."),
    "Dyrroth": ("SITUATIONAL", "B", 4.0, "Anti-tank shred; bottom-tier comeback kit."),
    "Guinevere": ("VIABLE", "B", 6.0, "Clone-bait dives; punished by true sight."),
    "Esmeralda": ("STRONG", "A", 6.5, "Shield-strip beats sustain EXPs. Stable pick."),
    "Freya": ("STRONG", "A", 6.5, "Valkyrie burst on demand. Respect her 8."),
    "Yin": ("VIABLE", "B", 6.0, "Duel arena takeaways; draft around immunities."),
}
